### ISSUE TITLE
Use common styling for video cards and the subtitle card

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#260]
Styling for the subtitle card is based on the styling for the video card, with some changes made to make it resemble what's shown in the design mockups.  There might be a way to come up with common styles for both to some extent.

**Comment by Ferdi** [comment]
@mbertrand can you elaborate a bit more pls ?

**Comment by mbertrand** [comment]
VideoSubtitleCards use styles like:
```css
.video-subtitles {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: space-around;
  width: 100%;
  align-items: stretch;
}
```
which is based on the styling for video cards:
```css
.videos {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: flex-start;
  width: 100%;
  align-items: stretch;
}
```

It might be good to put the style attributes shared by both into common styles that can be shared by both:
```css
.card-container {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  width: 100%;
  align-items: stretch;
}
.video-subtitles {
  justify-content: space-around;
}
.videos {
  justify-content: flex-start;
}
```

```html
<VideoCard className="card-container videos" />
<VideoSubtitleCard className="card-container video-subtitles" />
```
